//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gimnasio_app
{


    public partial class SesionesEntrenamiento
    {

        /// <summary>
        /// Control ddlRutina.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRutina;

        /// <summary>
        /// Control txtDesde.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDesde;

        /// <summary>
        /// Control txtHasta.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHasta;

        /// <summary>
        /// Control btnFiltrar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnFiltrar;

        /// <summary>
        /// Control btnLimpiar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLimpiar;

        /// <summary>
        /// Control lnkSortRutina.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkSortRutina;

        /// <summary>
        /// Control litCaretRutina.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCaretRutina;

        /// <summary>
        /// Control lnkSortFecha.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkSortFecha;

        /// <summary>
        /// Control litCaretFecha.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCaretFecha;

        /// <summary>
        /// Control rptSesiones.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptSesiones;

        /// <summary>
        /// Control phSinSesiones.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phSinSesiones;
    }
}
